######################################################################
# Automatically generated by qmake (1.07a) Fri Nov 5 11:57:59 2010
######################################################################
QT  +=  widgets
QT += widgets multimedia
#include <QtWidgets>
TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h\
					 mainpaint.h
SOURCES += mainwindow.cpp\
					 mainpaint.cpp\
					 main.cpp
