######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 8 00:20:09 2014
######################################################################
QT  +=  widgets
TEMPLATE = app
TARGET =    photo2
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dlinklist.h qt1.h dlinklist.c
FORMS += qt1.ui
SOURCES += dlinklist.c main.cpp qt1.cpp
